package com.prismtech.edison.sensor.types;


/**
* com/prismtech/edison/sensor/types/AnalogSensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl//sensor.idl
* Tuesday, February 16, 2016 1:52:37 AM CET
*/

/**
* Updated by idl2j
* from ../idl//sensor.idl
* Tuesday, February 16, 2016 1:52:38 AM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "AnalogSensor",
    keys = {"id"}
)
public final class AnalogSensor implements org.omg.CORBA.portable.IDLEntity
{
  public short id = (short)0;
  public float rvalue = (float)0;
  public float value = (float)0;

  public AnalogSensor ()
  {
  } // ctor

  public AnalogSensor (short _id, float _rvalue, float _value)
  {
    id = _id;
    rvalue = _rvalue;
    value = _value;
  } // ctor

} // class AnalogSensor
