package com.prismtech.edison.sensor.types;

/**
* com/prismtech/edison/sensor/types/AnalogSensorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl//sensor.idl
* Tuesday, February 16, 2016 1:52:37 AM CET
*/

public final class AnalogSensorHolder implements org.omg.CORBA.portable.Streamable
{
  public com.prismtech.edison.sensor.types.AnalogSensor value = null;

  public AnalogSensorHolder ()
  {
  }

  public AnalogSensorHolder (com.prismtech.edison.sensor.types.AnalogSensor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.prismtech.edison.sensor.types.AnalogSensorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.prismtech.edison.sensor.types.AnalogSensorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.prismtech.edison.sensor.types.AnalogSensorHelper.type ();
  }

}
