package com.prismtech.edison.sensor.types;


/**
* com/prismtech/edison/sensor/types/AnalogSensorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl//sensor.idl
* Tuesday, February 16, 2016 1:52:37 AM CET
*/

abstract public class AnalogSensorHelper
{
  private static String  _id = "IDL:com/prismtech/edison/sensor/types/AnalogSensor:1.0";

  public static void insert (org.omg.CORBA.Any a, com.prismtech.edison.sensor.types.AnalogSensor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.prismtech.edison.sensor.types.AnalogSensor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "rvalue",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[2] = new org.omg.CORBA.StructMember (
            "value",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.prismtech.edison.sensor.types.AnalogSensorHelper.id (), "AnalogSensor", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.prismtech.edison.sensor.types.AnalogSensor read (org.omg.CORBA.portable.InputStream istream)
  {
    com.prismtech.edison.sensor.types.AnalogSensor value = new com.prismtech.edison.sensor.types.AnalogSensor ();
    value.id = istream.read_short ();
    value.rvalue = istream.read_float ();
    value.value = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.prismtech.edison.sensor.types.AnalogSensor value)
  {
    ostream.write_short (value.id);
    ostream.write_float (value.rvalue);
    ostream.write_float (value.value);
  }

}
