#!/bin/bash
source ./bin/version

rm -Rf ./jars &>/dev/null
mkdir ./jars
find . -name "*$AGENTV_VERSION.jar" -exec cp {} ./lib/ &> /dev/null \;

cp lib/agentv-core-types_2.11-${AGENTV_VERSION}.jar ./bin/repository
cp lib/agentv-runtime-assembly-${AGENTV_VERSION}.jar ./bin/repository
cp lib/agentv-assembly-${AGENTV_VERSION}.jar ./bin/repository

