package com.prismtech.edison.display.types;


/**
* com/prismtech/edison/display/types/LCDColor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl//display.idl
* Tuesday, February 16, 2016 1:52:37 AM CET
*/

/**
* Updated by idl2j
* from ../idl//display.idl
* Tuesday, February 16, 2016 1:52:37 AM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "LCDColor",
    keys = {"id"}
)
public final class LCDColor implements org.omg.CORBA.portable.IDLEntity
{
  public short id = (short)0;
  public short r = (short)0;
  public short g = (short)0;
  public short b = (short)0;

  public LCDColor ()
  {
  } // ctor

  public LCDColor (short _id, short _r, short _g, short _b)
  {
    id = _id;
    r = _r;
    g = _g;
    b = _b;
  } // ctor

} // class LCDColor
