package com.prismtech.edison.led.types;


/**
* com/prismtech/edison/led/types/LED.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl//LED.idl
* Tuesday, February 16, 2016 1:52:36 AM CET
*/

/**
* Updated by idl2j
* from ../idl//LED.idl
* Tuesday, February 16, 2016 1:52:36 AM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "LED",
    keys = {"id"}
)
public final class LED implements org.omg.CORBA.portable.IDLEntity
{
  public short id = (short)0;
  public boolean on = false;

  public LED ()
  {
  } // ctor

  public LED (short _id, boolean _on)
  {
    id = _id;
    on = _on;
  } // ctor

} // class LED
