package com.prismtech.edison.led.types;

/**
* com/prismtech/edison/led/types/LEDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl//LED.idl
* Tuesday, February 16, 2016 1:52:36 AM CET
*/

public final class LEDHolder implements org.omg.CORBA.portable.Streamable
{
  public com.prismtech.edison.led.types.LED value = null;

  public LEDHolder ()
  {
  }

  public LEDHolder (com.prismtech.edison.led.types.LED initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.prismtech.edison.led.types.LEDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.prismtech.edison.led.types.LEDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.prismtech.edison.led.types.LEDHelper.type ();
  }

}
